name: learn-github-actions
on:
  workflow_dispatch:
    inputs:
      name:
        description: enter your name
      password:
        description: enter password

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "you entered name':' ${{ github.event.inputs.name }}"
      - run: echo "you entered name':' ${{ github.event.inputs.password }}"
  
  job2:
    if: github.event.inputs.name == 'yashodhan' && github.event.inputs.password == 'yash@123'
    runs-on: ubuntu-latest
    steps: 
      - run: echo "hello ${{ github.event.inputs.name }}, your vallid user"
      
  job3:
    if: github.event.inputs.name != 'yashodhan' && github.event.inputs.password != 'yash@123'
    runs-on: ubuntu-latest
    steps: 
      - run: echo "hello ${{ github.event.inputs.name }}, your not vallid user"
