name: learn-github-actions
on:
  workflow_dispatch:
    inputs:
      name:
        description: enter your name
        required: true
    
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps: [run: echo "${{ github.event.inputs.name }}"]
